description: Template to install Bluwave-ai DAIR BoosterPack Flight Plan
heat_template_version: 2018-03-02
# Adapted from Morpheus Blueprint for 
# https://www.canarie.ca/cloud/boosterpacks/catalogue/time-series-prediction-with-machine-learning/sample-solution-time-series-prediction-with-machine-learning/

parameters:
  my_flavor:
    type: string
    label: Flavor / Instance Type
    description: Size or Type of Instance to create
    default: v3.medium
    constraints:
      - allowed_values: [ v3.medium, v3.mediumx2, v3.mediumx4, v3.mediumx8, v3.large, v3.largex2, v3.largex4, v3.largex8 ]
        description: Value must be one of v3.medium or v3.large (or derivatives)

  my_image:
    type: string
    label: Image
    description: Image to Use
    default: Ubuntu 20.04 - 510

resources:
  my_key:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: t_series_key

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security Group for Bluwave-ai 
      name: bluwave_security_group
      rules:
        - direction: ingress
          ethertype: IPv4
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          ethertype: IPv4
          protocol: icmp
          remote_ip_prefix: 0.0.0.0/0

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: public

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: {get_attr: [instance, addresses, default, 0, port]}

  instance:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: my_flavor }
      key_name: { get_resource: my_key }
      image: { get_param: my_image }
      security_groups:
        - { get_resource: security_group }
      networks:
        - network: default
      user_data: |
        #!/bin/bash
        wall "Completing Install"
        touch /home/ubuntu/still_installing
        echo -n | openssl s_client -showcerts -connect code.cloud.canarie.ca:3000 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/gogs.pem
        mv ~/gogs.pem /etc/ssl/certs/GOGS.pem
        mkdir /home/tsp
        wall "Cloning Time Series Repo"
        git clone https://code.cloud.canarie.ca:3000/bluwave-ai/time-series-prediction.git /home/tsp/time-series-prediction
        chmod o+w -R /home/tsp/time-series-prediction
        wall "Installing MiniConda"
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /home/tsp/
        bash /home/tsp/Miniconda3-latest-Linux-x86_64.sh -b -p /home/tsp/miniconda
        wall "Creating TSP Environments"
        export PATH="/home/tsp/miniconda/bin:$PATH"
        source "/home/tsp/miniconda/bin/activate"
        conda init
        exec bash
        cd /home/tsp/time-series-prediction/energy-prediction
        make create_environment
        cd /home/tsp/time-series-prediction/weather-prediction
        make create_environment
        mv /home/ubuntu/still_installing /home/ubuntu/install_complete

outputs:
  instance_detail:
    description: 
    value: { get_attr: [instance, show] }

  private_key:
    description: Private key
    value: { get_attr: [ my_key, private_key ] }

