description: Template to install Bluwave-ai DAIR BoosterPack Flight Plan
heat_template_version: 2018-03-02
# Adapted from Morpheus Blueprint for 
# https://www.canarie.ca/cloud/boosterpacks/catalogue/time-series-prediction-with-machine-learning/sample-solution-time-series-prediction-with-machine-learning/
# Shawn Ayotte 2023

resources:
  my_key:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: t_series_key

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Security Group for Bluwave-ai 
      name: bluwave_security_group
      rules:
        - direction: ingress
          ethertype: IPv4
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          ethertype: IPv6
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: ::/0
        - direction: ingress
          ethertype: IPv4
          protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          ethertype: IPv6
          protocol: icmp
          remote_ip_prefix: ::/0
  instance:
    type: OS::Nova::Server
    properties:
      flavor: "v2.medium"
      key_name: { get_resource: my_key }
      image: "Ubuntu 20.04 - 510"
      security_groups:
        - { get_resource: security_group }
      networks:
        - network: public
      # user_data_format: RAW
      user_data: |
        #!/bin/bash
        wall "Completing Install"
        touch /home/ubuntu/still_installing
        echo -n | openssl s_client -showcerts -connect code.cloud.canarie.ca:3000 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/gogs.pem
        mv ~/gogs.pem /etc/ssl/certs/GOGS.pem
        mkdir /home/tsp
        wall "Cloning Time Series Repo"
        git clone https://code.cloud.canarie.ca:3000/bluwave-ai/time-series-prediction.git /home/tsp/time-series-prediction
        chmod o+w -R /home/tsp/time-series-prediction
        wall "Installing MiniConda"
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -P /home/tsp/
        bash /home/tsp/Miniconda3-latest-Linux-x86_64.sh -b -p /home/tsp/miniconda
        wall "Creating TSP Environments"
        export PATH="/home/tsp/miniconda/bin:$PATH"
        source "/home/tsp/miniconda/bin/activate"
        conda init
        exec bash
        cd /home/tsp/time-series-prediction/energy-prediction
        make create_environment
        cd /home/tsp/time-series-prediction/weather-prediction
        make create_environment
        mv /home/ubuntu/still_installing /home/ubuntu/install_complete

outputs:
  instance_detail:
    description: 
    value: { get_attr: [instance, show] }

  private_key:
    description: Private key
    value: { get_attr: [ my_key, private_key ] }

